-- MySQL Script generated by MySQL Workbench
-- Mon Jun  7 16:13:06 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Hotel
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Hotel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Hotel` DEFAULT CHARACTER SET utf8 ;
USE `Hotel` ;

-- -----------------------------------------------------
-- Table `Hotel`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hotel`.`client` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `patronymic` VARCHAR(45) NULL,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hotel`.`status_request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hotel`.`status_request` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status_request` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hotel`.`manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hotel`.`manager` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `patrinymic` VARCHAR(45) NULL,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hotel`.`request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hotel`.`request` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `client_id` INT NOT NULL,
  `status_request_id` INT NOT NULL,
  `manager_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_request_client1_idx` (`client_id` ASC) VISIBLE,
  INDEX `fk_request_status_request1_idx` (`status_request_id` ASC) VISIBLE,
  INDEX `fk_request_manager1_idx` (`manager_id` ASC) VISIBLE,
  CONSTRAINT `fk_request_client1`
    FOREIGN KEY (`client_id`)
    REFERENCES `Hotel`.`client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_request_status_request1`
    FOREIGN KEY (`status_request_id`)
    REFERENCES `Hotel`.`status_request` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_request_manager1`
    FOREIGN KEY (`manager_id`)
    REFERENCES `Hotel`.`manager` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hotel`.`apartment_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hotel`.`apartment_status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hotel`.`booking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hotel`.`booking` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `client_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_booking_client1_idx` (`client_id` ASC) VISIBLE,
  CONSTRAINT `fk_booking_client1`
    FOREIGN KEY (`client_id`)
    REFERENCES `Hotel`.`client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hotel`.`apartment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hotel`.`apartment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `apartment_status_id` INT NOT NULL,
  `price` VARCHAR(45) NULL,
  `places` VARCHAR(45) NULL,
  `request_id` INT NOT NULL,
  `booking_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_apartment_apartment_status_idx` (`apartment_status_id` ASC) VISIBLE,
  INDEX `fk_apartment_request1_idx` (`request_id` ASC) VISIBLE,
  INDEX `fk_apartment_booking1_idx` (`booking_id` ASC) VISIBLE,
  CONSTRAINT `fk_apartment_apartment_status`
    FOREIGN KEY (`apartment_status_id`)
    REFERENCES `Hotel`.`apartment_status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_apartment_request1`
    FOREIGN KEY (`request_id`)
    REFERENCES `Hotel`.`request` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_apartment_booking1`
    FOREIGN KEY (`booking_id`)
    REFERENCES `Hotel`.`booking` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hotel`.`apartment_class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hotel`.`apartment_class` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `class` VARCHAR(45) NULL,
  `apartment_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_apartment_class_apartment1_idx` (`apartment_id` ASC) VISIBLE,
  CONSTRAINT `fk_apartment_class_apartment1`
    FOREIGN KEY (`apartment_id`)
    REFERENCES `Hotel`.`apartment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
